[project]
name = "pan-american-athletics-hub"
version = "0.1.0"
requires-python = ">=3.11,<3.13"
description = "Backend for the Pan-American Athletics Hub"
dependencies = []

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

